# Per-env SSM parameters consumed by the ahand-hub ECS task definition.
#
# Secrets are generated by Terraform via random_password so operators never
# have to handle them — ecs.tf's task definition injects them through
# secrets[] (execution role has ssm:GetParameters + kms:Decrypt).
#
# DATABASE_URL lives in rds.tf (placeholder, operator-seeded).
# REDIS_URL lives in redis.tf (derived from the cluster endpoint).
# SENTRY_DSN has a Terraform-managed resource but ignore_changes=[value]
# so the real DSN is populated once Sentry is configured, without drift.

resource "random_password" "jwt_secret" {
  length           = 48
  special          = true
  override_special = "!@#$%^&*_-+=."
}

resource "random_password" "service_token" {
  length           = 48
  special          = true
  override_special = "!@#$%^&*_-+=."
}

resource "random_password" "webhook_secret" {
  length           = 48
  special          = true
  override_special = "!@#$%^&*_-+=."
}

resource "random_password" "dashboard_password" {
  length           = 32
  special          = true
  override_special = "!@#$%^&*_-+=."
}

resource "random_password" "device_bootstrap_token" {
  length           = 32
  special          = true
  override_special = "!@#$%^&*_-+=."
}

resource "aws_ssm_parameter" "jwt_secret" {
  name  = "/ahand-hub/${var.env}/JWT_SECRET"
  type  = "SecureString"
  value = random_password.jwt_secret.result
  tags  = local.common_tags
}

resource "aws_ssm_parameter" "service_token" {
  name  = "/ahand-hub/${var.env}/SERVICE_TOKEN"
  type  = "SecureString"
  value = random_password.service_token.result
  tags  = local.common_tags
}

resource "aws_ssm_parameter" "webhook_secret" {
  name  = "/ahand-hub/${var.env}/WEBHOOK_SECRET"
  type  = "SecureString"
  value = random_password.webhook_secret.result
  tags  = local.common_tags
}

resource "aws_ssm_parameter" "dashboard_password" {
  name  = "/ahand-hub/${var.env}/DASHBOARD_PASSWORD"
  type  = "SecureString"
  value = random_password.dashboard_password.result
  tags  = local.common_tags
}

resource "aws_ssm_parameter" "device_bootstrap_token" {
  name  = "/ahand-hub/${var.env}/DEVICE_BOOTSTRAP_TOKEN"
  type  = "SecureString"
  value = random_password.device_bootstrap_token.result
  tags  = local.common_tags
}

resource "aws_ssm_parameter" "device_bootstrap_device_id" {
  name  = "/ahand-hub/${var.env}/DEVICE_BOOTSTRAP_DEVICE_ID"
  type  = "String"
  value = "disabled-bootstrap-placeholder"
  tags  = local.common_tags

  # The hub binary reads this but the team9 gateway is the real token-minter
  # in the MVP flow. Operators can override via put-parameter without
  # fighting Terraform.
  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "webhook_url" {
  name = "/ahand-hub/${var.env}/WEBHOOK_URL"
  type = "String"
  # Default value derives from gateway_public_url with the NestJS URI-version
  # path the gateway exposes (defaultVersion='1' → /api/v1/ahand/hub-webhook).
  # ignore_changes lets the operator pin a different value via put-parameter
  # without Terraform reverting it on subsequent applies — same pattern as
  # database_url, sentry_dsn, device_bootstrap_device_id.
  value = "${var.gateway_public_url}/api/v1/ahand/hub-webhook"
  tags  = local.common_tags

  lifecycle {
    ignore_changes = [value]
  }
}

resource "aws_ssm_parameter" "sentry_dsn" {
  name  = "/ahand-hub/${var.env}/SENTRY_DSN"
  type  = "SecureString"
  value = "PLACEHOLDER_SET_MANUALLY_AFTER_SENTRY_PROJECT_CREATED"
  tags  = local.common_tags

  lifecycle {
    ignore_changes = [value]
  }
}
